CREATE TABLE role (
	id INT(5) NOT NULL PRIMARY KEY auto_increment,
	name VARCHAR(50) NOT NULL,
	description TEXT
)ENGINE=INNODB;


CREATE TABLE user (
	id INTEGER(5) NOT NULL PRIMARY KEY auto_increment,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	id_role INTEGER(5) NOT NULL,
	FOREIGN KEY (id_role) REFERENCES role(id)
	ON DELETE CASCADE ON UPDATE CASCADE	
)ENGINE=INNODB;

CREATE TABLE profile (
	id INTEGER(5) NOT NULL PRIMARY KEY auto_increment,
	fullname VARCHAR(50) NOT NULL,
	email VARCHAR(50),
	phone VARCHAR(50),
	address TEXT,
	id_user INTEGER(5) NOT NULL,
	FOREIGN KEY (id_user) REFERENCES user(id)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE event (
	id INTEGER(5) NOT NULL PRIMARY KEY auto_increment,
	title VARCHAR(50) NOT NULL,
	description TEXT NOT NULL,
	lat VARCHAR(100) NOT NULL,
	lng VARCHAR(100) NOT NULL,
	reference_url VARCHAR(255) NOT NULL,
	id_user INTEGER(5) NOT NULL,
	FOREIGN KEY (id_user) REFERENCES user(id)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB;